[package]
name = "agntcy-slim-signal"
edition = { workspace = true }
license = { workspace = true }
version = "0.1.2"
description = "Small library to handle OS signals."

[lib]
name = "slim_signal"

[features]
default = ["native"]
native = ["tokio"]
wasm = []

[dependencies]
tokio = { version = "1", features = ["macros", "signal"], optional = true }
tracing = { workspace = true }
