[package]
name = "agntcy-slim-mls"
edition = { workspace = true }
license = { workspace = true }
version = "0.1.0"
description = "Messaging Layer Security for SLIM data plane."

[lib]
name = "slim_mls"

[features]
default = ["native"]
native = [
    "dep:mls-rs-crypto-awslc",
    "agntcy-slim-auth/native",
]
wasm = [
    "dep:mls-rs-crypto-webcrypto",
    "agntcy-slim-auth/wasm",
]

[dependencies]
agntcy-slim-auth = { workspace = true, default-features = false }
async-trait = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
maybe-async = { workspace = true }
mls-rs = { workspace = true }
mls-rs-core = { workspace = true }
mls-rs-crypto-awslc = { workspace = true, optional = true }
mls-rs-crypto-webcrypto = { workspace = true, optional = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3.3"

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ["cfg(mls_build_async)"]
