[package]
name = "agntcy-slim-controller"
edition = { workspace = true }
license = { workspace = true }
version = "0.1.1"
description = "Controller service and control API to configure the SLIM data plane through the control plane."

[lib]
name = "slim_controller"

[features]
default = ["native"]
native = [
    "agntcy-slim-config/native",
    "agntcy-slim-datapath/native",
    "dep:bytes",
    "dep:h2",
    "dep:tokio",
    "dep:tokio-stream",
    "dep:tokio-util",
    "dep:tonic",
]
wasm = [
    "agntcy-slim-config/wasm",
    "agntcy-slim-datapath/wasm",
]

[dependencies]
agntcy-slim-config = { workspace = true, default-features = false }
agntcy-slim-datapath = { workspace = true, default-features = false }
bytes = { workspace = true, optional = true }
h2 = { workspace = true, optional = true }
parking_lot = { workspace = true }
prost = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"], optional = true }
tokio-stream = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
tonic = { workspace = true, optional = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[build-dependencies]
protoc-bin-vendored = { workspace = true }
tonic-build = { workspace = true, features = ["prost"] }
