[package]
name = "slim-examples"
version = "0.1.0"
edition = { workspace = true }
publish = false

[[bin]]
name = "sdk-mock"
path = "src/sdk-mock/main.rs"

[dependencies]
agntcy-slim = { workspace = true }
agntcy-slim-config = { workspace = true, features = ["native"] }
agntcy-slim-datapath = { workspace = true, features = ["native"] }
agntcy-slim-service = { workspace = true, features = ["native"] }
agntcy-slim-signal = { workspace = true, features = ["native"] }
clap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
